import os


TELEGRAM_USERNAME_WHITELIST = os.environ['TELEGRAM_USERNAME_WHITELIST'].split(',')
TELEGRAM_TOKEN = os.environ['TELEGRAM_TOKEN']
NOTIFICATION_JOB_QUEUE_INTERVAL_SECONDS = int(os.environ['NOTIFICATION_JOB_QUEUE_INTERVAL_SECONDS'])
NOTIFICATION_JOB_QUEUE_FIRST_SECONDS = int(os.environ['NOTIFICATION_JOB_QUEUE_FIRST_SECONDS'])
NOTIFY_IF_UNFED_FOR_SECONDS = int(os.environ['NOTIFY_IF_UNFED_FOR_SECONDS'])